name: CI Nginx Test

# триггер: только при изменении index.html
on:
  push:
    paths:
      - "index.html"

jobs:
  build-and-test:
    runs-on: self-hosted   # запускается на виртуалке
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        run: |
          sudo apt update
          sudo apt install -y docker.io

      - name: Run Nginx container
        run: |
          docker run -d --name ci-nginx -p 9889:80 -v $PWD/index.html:/usr/share/nginx/html/index.html:ro nginx:alpine

      - name: Wait for Nginx to start
        run: sleep 5

      - name: Check HTTP response
        id: http_check
        run: |
          CODE=$(curl -o /dev/null -s -w "%{http_code}" http://localhost:9889)
          echo "HTTP_CODE=$CODE" >> $GITHUB_ENV
          if [ "$CODE" -ne 200 ]; then
            echo "HTTP code is not 200!"
            exit 1
          fi

      - name: Compare MD5 checksum
        run: |
          ORIGINAL_MD5=$(md5sum index.html | awk '{print $1}')
          NGINX_MD5=$(curl -s http://localhost:9889/index.html | md5sum | awk '{print $1}')
          echo "Original: $ORIGINAL_MD5"
          echo "From Nginx: $NGINX_MD5"
          if [ "$ORIGINAL_MD5" != "$NGINX_MD5" ]; then
            echo "MD5 checksums do not match!"
            exit 1
          fi

      - name: Notify on failure
        if: failure()
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: |
          curl -s -X POST "https://api.telegram.org/bot${TG_TOKEN}/sendMessage" \
            -d chat_id="${TG_CHAT_ID}" \
            -d text="❌ CI failed for repository $GITHUB_REPOSITORY at commit $GITHUB_SHA"

      - name: Cleanup
        run: |
          docker stop ci-nginx
          docker rm ci-nginx
