name: Test Telegram Notification

on:
  push:
    branches:
      - main

jobs:
  test-telegram:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Force failure
        run: |
          echo "Force failure for Telegram test"
          exit 1

      - name: Notify on failure
        if: failure()
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: |
          echo "Sending Telegram message"
          curl -s -X POST "https://api.telegram.org/bot${TG_TOKEN}/sendMessage" \
          -d chat_id="${TG_CHAT_ID}" \
          -d text="❌ CI failed for repository $GITHUB_REPOSITORY at commit $GITHUB_SHA"
